FROM node:16-alpine
WORKDIR /usr/src/app
COPY package.json yarn.lock requirements.txt ./

RUN apk add --update --no-cache --virtual .build-deps \
      # better-sqlite3
      build-base \
      python3 \
      py3-pip \
      python3-dev \
 && pip3 install --requirement requirements.txt \
 && yarn install \
 && yarn cache clean \
 && apk del .build-deps \
 && apk add --update --no-cache \
      python3

COPY . ./

RUN yarn build \
 && yarn bundle \
 && mkdir /database \
 && ln -s /database database \
 && mkdir /storage \
 && ln -s /storage storage

ENTRYPOINT ["yarn"]
